package com.example.zhangshuyang01.greendaodemo2.bean.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.zhangshuyang01.greendaodemo2.bean.User;
import com.example.zhangshuyang01.greendaodemo2.bean.Student;
import com.example.zhangshuyang01.greendaodemo2.bean.Books;
import com.example.zhangshuyang01.greendaodemo2.bean.Client;
import com.example.zhangshuyang01.greendaodemo2.bean.Commande;

import com.example.zhangshuyang01.greendaodemo2.bean.greendao.UserDao;
import com.example.zhangshuyang01.greendaodemo2.bean.greendao.StudentDao;
import com.example.zhangshuyang01.greendaodemo2.bean.greendao.BooksDao;
import com.example.zhangshuyang01.greendaodemo2.bean.greendao.ClientDao;
import com.example.zhangshuyang01.greendaodemo2.bean.greendao.CommandeDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig studentDaoConfig;
    private final DaoConfig booksDaoConfig;
    private final DaoConfig clientDaoConfig;
    private final DaoConfig commandeDaoConfig;

    private final UserDao userDao;
    private final StudentDao studentDao;
    private final BooksDao booksDao;
    private final ClientDao clientDao;
    private final CommandeDao commandeDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        studentDaoConfig = daoConfigMap.get(StudentDao.class).clone();
        studentDaoConfig.initIdentityScope(type);

        booksDaoConfig = daoConfigMap.get(BooksDao.class).clone();
        booksDaoConfig.initIdentityScope(type);

        clientDaoConfig = daoConfigMap.get(ClientDao.class).clone();
        clientDaoConfig.initIdentityScope(type);

        commandeDaoConfig = daoConfigMap.get(CommandeDao.class).clone();
        commandeDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        studentDao = new StudentDao(studentDaoConfig, this);
        booksDao = new BooksDao(booksDaoConfig, this);
        clientDao = new ClientDao(clientDaoConfig, this);
        commandeDao = new CommandeDao(commandeDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Student.class, studentDao);
        registerDao(Books.class, booksDao);
        registerDao(Client.class, clientDao);
        registerDao(Commande.class, commandeDao);
    }
    
    public void clear() {
        userDaoConfig.clearIdentityScope();
        studentDaoConfig.clearIdentityScope();
        booksDaoConfig.clearIdentityScope();
        clientDaoConfig.clearIdentityScope();
        commandeDaoConfig.clearIdentityScope();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public StudentDao getStudentDao() {
        return studentDao;
    }

    public BooksDao getBooksDao() {
        return booksDao;
    }

    public ClientDao getClientDao() {
        return clientDao;
    }

    public CommandeDao getCommandeDao() {
        return commandeDao;
    }

}
